// The site's home page is the README, transformed — not a second copy of it.
//
// Three surfaces show the same page: the repository, npmjs.com (which renders
// README.md from the tarball) and the documentation site. Two of those come
// from one file for free; the third used to be a hand-maintained copy, which
// is a promise to keep two files saying the same thing forever. Nobody keeps
// that promise.
//
// So docs/index.md is generated here, and test/site-home.test.ts fails when it
// has drifted. Run `npm run docs:sync` after editing the README.
//
// What the site needs that the README cannot have: relative links between
// pages, the image at its site-relative path, and package-manager tabs, which
// GitHub does not render. The README marks that one region with
// <!-- install:start --> so this can swap it.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://atamaniuc.github.io/Harnessimo/";
const REPO = "https://github.com/atamaniuc/Harnessimo/blob/main/";

const HEADER = `<!--
  Generated from README.md by scripts/site-home.ts. Do not edit this file:
  edit the README and run \`npm run docs:sync\`. test/site-home.test.ts fails
  when the two have drifted.
-->
`;

/** The site plays the recording; GitHub and npm can only show a still of it. */
const PLAYER = `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/asciinema-player@3.8.0/dist/bundle/asciinema-player.min.css">
<div id="demo" class="demo-player"></div>
<script src="https://cdn.jsdelivr.net/npm/asciinema-player@3.8.0/dist/bundle/asciinema-player.min.js"></script>
<script>
  AsciinemaPlayer.create("/Harnessimo/assets/demo.cast", document.getElementById("demo"), {
    autoPlay: true, loop: true, idleTimeLimit: 1.2, terminalFontSize: "14px", theme: "nord",
  });
</script>
`;

const PLAYER_CAPTION: Record<string, string> = {
  en: "Nobody scripted that: `npm run demo` runs those commands in a throwaway repository and\nrecords what they print.",
  ru: "Это никто не писал вручную: `npm run demo` запускает эти команды во временном\nрепозитории и записывает то, что они напечатали.",
};

/** The install block, as tabs — one per package manager. */
const INSTALL_TABS = [
  ["pnpm", "pnpm add -D harnessimo", "pnpm exec harnessimo"],
  ["npm", "npm i -D harnessimo", "npx harnessimo"],
  ["yarn", "yarn add -D harnessimo", "yarn harnessimo"],
  ["bun", "bun add -d harnessimo", "bunx harnessimo"],
]
  .map(([name, install, run]) => {
    const width = Math.max(`${run} init`.length, `${run} check`.length);
    const body = [
      install,
      `${`${run} init`.padEnd(width)}   # scans your repo, writes a config that already passes`,
      `${`${run} check`.padEnd(width)}   # run this in CI`,
    ];
    const block = ["```bash", ...body, "```"].map((line) => `    ${line}`).join("\n");
    return `=== "${name}"\n\n${block}\n`;
  })
  .join("\n")
  .trimEnd();

/** Languages this generates a home page for: the README, and its translations. */
export const LANGUAGES = [
  { locale: "en", readme: "README.md", page: "docs/index.md" },
  { locale: "ru", readme: "README.ru.md", page: "docs/index.ru.md" },
];

export function siteHome(readme: string, locale = "en"): string {
  let text = readme;

  // The site has a language switcher in its header, so the link the README
  // files carry for each other is noise there.
  const langStart = text.indexOf("<!-- lang:start -->");
  const langEnd = text.indexOf("<!-- lang:end -->");
  if (langStart !== -1 && langEnd !== -1) {
    text = text.slice(0, langStart) + text.slice(langEnd + "<!-- lang:end -->".length).trimStart();
  }

  const demoStart = text.indexOf("<!-- demo:start -->");
  const demoEnd = text.indexOf("<!-- demo:end -->");
  if (demoStart === -1 || demoEnd === -1) {
    throw new Error("README.md has no <!-- demo:start --> … <!-- demo:end --> region");
  }
  text =
    text.slice(0, demoStart) +
    PLAYER +
    (PLAYER_CAPTION[locale] ?? PLAYER_CAPTION.en) +
    text.slice(demoEnd + "<!-- demo:end -->".length);

  const start = text.indexOf("<!-- install:start -->");
  const end = text.indexOf("<!-- install:end -->");
  if (start === -1 || end === -1) {
    throw new Error("README.md has no <!-- install:start --> … <!-- install:end --> region");
  }
  text = text.slice(0, start) + INSTALL_TABS + text.slice(end + "<!-- install:end -->".length);

  // Site pages link to each other, not out to the published site. Page names
  // are upper-case by convention, which is what separates them from a language
  // root like /ru/ — that is a site, not a page, and rewriting it produces a
  // link to nothing. Matched by shape rather than by a list: a list of pages
  // kept in a generator is one more thing that silently falls behind the pages.
  // Both languages: a Russian page links to Russian pages, and the plugin
  // resolves the plain name inside the language it is building.
  text = text.replace(new RegExp(`${SITE}(?:[a-z]{2}/)?([A-Z][A-Z0-9-]*)/`, "g"), "$1.md");
  text = text.replace(`(${SITE})`, "(index.md)");
  // The image lives under docs/, so its path loses that prefix.
  text = text.replace(/src="docs\/assets\//g, 'src="assets/');
  // Files that exist in the repository but not on the site.
  text = text.replace(
    /\]\((LICENSE|CONTRIBUTING\.md|package\.json|README\.md|README\.ru\.md)\)/g,
    `](${REPO}$1)`,
  );

  return HEADER + text;
}

const checking = process.argv.includes("--check");
for (const language of LANGUAGES) {
  const generated = siteHome(readFileSync(join(ROOT, language.readme), "utf8"), language.locale);
  const target = join(ROOT, language.page);
  if (checking) {
    if (readFileSync(target, "utf8") !== generated) {
      console.error(
        `${language.page} is not what ${language.readme} generates.\n` +
          "  fix:  npm run docs:sync, and commit the result with the README change",
      );
      process.exit(1);
    }
    console.log(`${language.page} matches ${language.readme}`);
  } else {
    writeFileSync(target, generated);
    console.log(`wrote ${language.page} from ${language.readme}`);
  }
}
