// The site's home page is the README, transformed — not a second copy of it.
//
// Three surfaces show the same page: the repository, npmjs.com (which renders
// README.md from the tarball) and the documentation site. Two of those come
// from one file for free; the third used to be a hand-maintained copy, which
// is a promise to keep two files saying the same thing forever. Nobody keeps
// that promise.
//
// So docs/index.md is generated here, and test/site-home.test.ts fails when it
// has drifted. Run `npm run docs:sync` after editing the README.
//
// What the site needs that the README cannot have: relative links between
// pages, the image at its site-relative path, and package-manager tabs, which
// GitHub does not render. The README marks that one region with
// <!-- install:start --> so this can swap it.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://atamaniuc.github.io/Harnessimo/";
const REPO = "https://github.com/atamaniuc/Harnessimo/blob/main/";

const HEADER = `<!--
  Generated from README.md by scripts/site-home.ts. Do not edit this file:
  edit the README and run \`npm run docs:sync\`. test/site-home.test.ts fails
  when the two have drifted.
-->
`;

/** The site plays the recording; GitHub and npm can only show a still of it. */
const PLAYER = `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/asciinema-player@3.8.0/dist/bundle/asciinema-player.min.css">
<div id="demo" class="demo-player"></div>
<script src="https://cdn.jsdelivr.net/npm/asciinema-player@3.8.0/dist/bundle/asciinema-player.min.js"></script>
<script>
  AsciinemaPlayer.create("/Harnessimo/assets/demo.cast", document.getElementById("demo"), {
    autoPlay: true, loop: true, idleTimeLimit: 1.2, terminalFontSize: "14px", theme: "nord",
  });
</script>

Nobody scripted that: \`npm run demo\` runs those commands in a throwaway repository and
records what they print.`;

/** The install block, as tabs — one per package manager. */
const INSTALL_TABS = [
  ["pnpm", "pnpm add -D harnessimo", "pnpm exec harnessimo"],
  ["npm", "npm i -D harnessimo", "npx harnessimo"],
  ["yarn", "yarn add -D harnessimo", "yarn harnessimo"],
  ["bun", "bun add -d harnessimo", "bunx harnessimo"],
]
  .map(([name, install, run]) => {
    const width = Math.max(`${run} init`.length, `${run} check`.length);
    const body = [
      install,
      `${`${run} init`.padEnd(width)}   # scans your repo, writes a config that already passes`,
      `${`${run} check`.padEnd(width)}   # run this in CI`,
    ];
    const block = ["```bash", ...body, "```"].map((line) => `    ${line}`).join("\n");
    return `=== "${name}"\n\n${block}\n`;
  })
  .join("\n")
  .trimEnd();

export function siteHome(readme: string): string {
  let text = readme;

  const demoStart = text.indexOf("<!-- demo:start -->");
  const demoEnd = text.indexOf("<!-- demo:end -->");
  if (demoStart === -1 || demoEnd === -1) {
    throw new Error("README.md has no <!-- demo:start --> … <!-- demo:end --> region");
  }
  text =
    text.slice(0, demoStart) + PLAYER + text.slice(demoEnd + "<!-- demo:end -->".length);

  const start = text.indexOf("<!-- install:start -->");
  const end = text.indexOf("<!-- install:end -->");
  if (start === -1 || end === -1) {
    throw new Error("README.md has no <!-- install:start --> … <!-- install:end --> region");
  }
  text = text.slice(0, start) + INSTALL_TABS + text.slice(end + "<!-- install:end -->".length);

  // Site pages link to each other, not out to the published site. Named
  // explicitly so a language root like /ru/ is left alone — that is a site, not
  // a page, and rewriting it produces a link to nothing.
  text = text.replace(
    new RegExp(`${SITE}(WHY|GUIDE|USE-CASES|SDD|STANDARD|ADOPTING)/`, "g"),
    "$1.md",
  );
  text = text.replace(`(${SITE})`, "(index.md)");
  // The image lives under docs/, so its path loses that prefix.
  text = text.replace(/src="docs\/assets\//g, 'src="assets/');
  // Files that exist in the repository but not on the site.
  text = text.replace(/\]\((LICENSE|CONTRIBUTING\.md|package\.json)\)/g, `](${REPO}$1)`);

  return HEADER + text;
}

const readme = readFileSync(join(ROOT, "README.md"), "utf8");
const generated = siteHome(readme);
const target = join(ROOT, "docs", "index.md");

if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8");
  if (current !== generated) {
    console.error(
      "docs/index.md is not what README.md generates.\n" +
        "  fix:  npm run docs:sync, and commit the result with the README change",
    );
    process.exit(1);
  }
  console.log("docs/index.md matches README.md");
} else {
  writeFileSync(target, generated);
  console.log("wrote docs/index.md from README.md");
}
